apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  generation: 1
  labels:
    app: gocd-agent-openshift
  name: gocd-agent-openshift
spec:
  replicas: 1
  selector:
    app: gocd-agent-openshift
    deploymentconfig: gocd-agent-openshift
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: gocd-agent-openshift
        deploymentconfig: gocd-agent-openshift
    spec:
      containers:
      - env:
        - name: GO_SERVER_URL
          value: https://gocd-server.cicd.svc:8154/go
        - name: DOCKER_HOST
          value: unix:///var/run/docker.sock
        image: docker-registry.default.svc:5000/cicd/gocd-agent-openshift@sha256:49024bbe0d1898b2f33957295cdb26effb160a426fe959d96ce448f27a4d18d2
        imagePullPolicy: Always
        name: gocd-agent-openshift
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: dockersock
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsUser: 0
      serviceAccount: privileged-deployer
      serviceAccountName: privileged-deployer
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /var/run/docker.sock
        name: dockersock
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - gocd-agent-openshift
      from:
        kind: ImageStreamTag
        name: gocd-agent-openshift:latest
        namespace: cicd
    type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
